### ISSUE TITLE
If you use hota17 theme, the mainmenu will disappear

### ISSUE THREAD

**Issue by lishaoxia1985** [vcmi-mods/h3-themes#1]

**Comment by Aph-ra** [comment]
Can you link a log of the console and mods list or provide any screenshots? I cannot replicate this bug, nor are there any console issues showing up. Do you have another main menu mod installed that is not on the mod conflict list?

**Comment by lishaoxia1985** [comment]
![Screenshot_20240624_093605_is.xyz.vcmi.daily.jpg](https://github.com/vcmi-mods/h3-themes/assets/49801619/3781d4d8-e78c-4c44-9392-106cd1d8fa33)

![Screenshot_20240624_093518_is.xyz.vcmi.daily.jpg](https://github.com/vcmi-mods/h3-themes/assets/49801619/061b0c49-0f51-437a-b39b-3f410977bb3f)

**Comment by Aph-ra** [comment]
I have tested this with only the mods you have enabled and I cannot replicate this bug on mobile (OnePlus 5 with daily VCMI build on 24/JUN/2024, tested on 100, 150, and 180% interface scaling) or PC (Windows 10, VCMI 1.5.3).

This mod has since been updated but it has not been pushed to the repo yet. Try downloading the latest version here: https://github.com/vcmi/vcmi-mods-repository/issues/51#issuecomment-2153527601

EDIT: new version with VCMI theme has been released here: https://github.com/vcmi/vcmi-mods-repository/issues/51#issuecomment-2186742076

If updating the mod does not work, please try updating to the latest VCMI build for your device.

If that also does not solve the problem, let me know.

**Comment by lishaoxia1985** [comment]
@Aph-ra I test. The problem still exists. Other theme runs very well except hota17.
Please check the file.
You can fix it with this:
if you copy the file "mainmenu.json" of hota16 to overwrite the file in hota17, it will run very well.
By the way, I use vcmi 1.6 on Android.

**Comment by Aph-ra** [comment]
I've had a look and the _only difference_ in the code between 1.6 theme and 1.7 theme's "mainmenu.json" is the inclusion of the animation (in BIK video format) for the 1.7 theme. I have removed the additional comment in the same line of code (even though that should not affect anything) and compared it with the WoG and SoD code and there is no difference besides video format.

See: https://github.com/vcmi/vcmi-mods-repository/issues/51#issuecomment-2189209463

It _could_ be that your device is not properly recognising the BIK video format correctly for some reason, despite BIK and SMK videos both being products of RAD Game Tools. I have changed the video format in the below version; the video quality is slightly lower with compression artifacts being introduced, but perhaps it'll work for you.

See: https://drive.google.com/file/d/1tzrqcXRb_cZK7CwrdnxZBJ4vX3bLoLH_/view?usp=sharing

**Comment by lishaoxia1985** [comment]
@Aph-ra I test.
It changes nothing. The problem still exists. The only fix method is what I have say.
![Screenshot_20240626_015009_is.xyz.vcmi.daily.jpg](https://github.com/vcmi-mods/h3-themes/assets/49801619/b9a592b3-df0a-45bd-aff8-90730ed40427)

If you change the position of video in the window, you will find the video cover the mainmenu.
That means the app put the video on the front of mainmenu, when the size of video is small and its position can't cover the mainmenu, it will runs well, for example Wog. If not, the video will cover the mainmenu.
I think it's a bug about app.
@IvanSavenko The app should put the widget in this order:
Background picture is on the bottom, and then it's the video, the mainmenu is on the top.

**Comment by Aph-ra** [comment]
Thank you for detailing this bug, and you're right, it may be an issue with the app itself, though it's strange that I cannot replicate it on any mobile device I have access to (I have also tried on a Samsung Galaxy Note 10 and 2 older Huawei devices). It may be to do with the specific version of VCMI you're using, hopefully the developer can confirm!
