### ISSUE TITLE
Beta

### ISSUE THREAD

**Issue by Laserlicht** [vcmi-mods/h3-themes#6]
Maybe someone want's to create a theme from beta background. :D

https://heroes3wog.net/wp-content/uploads/2016/04/menu-beta.jpg

https://heroes3wog.net/heroes-3-beta-screenshots/

**Comment by Olegmods** [comment]
> Maybe create a theme from beta background. :D
> 
> https://heroes3wog.net/wp-content/uploads/2016/04/menu-beta.jpg
> 
> https://heroes3wog.net/heroes-3-beta-screenshots/

Offtopic, but I feel the beta interface is a good idea too.

**Comment by Aph-ra** [comment]
I'll see what I can do ;)
